name       : perl-locale-maketext-lexicon
version    : 1.0
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DRTECH/Locale-Maketext-Lexicon-1.00.tar.gz : b73f6b04a58d3f0e38ebf2115a4c1532f1a4eef6fac5c6a2a449e4e14c1ddc7c
license    : MIT
component  : programming.perl
summary    : Use other catalog formats in Maketext
description: |
    This module provides lexicon-handling modules to read from other localization formats, such as *Gettext*, *Msgcat*, and so on.
    A command-line utility xgettext.pl is also installed with this module, for extracting translatable strings from source files.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
